[default]
    default.locale = "en_us"

    [default.extend-words]
        Enabledi = "Enabledi" # Context: com.apple.metadata
        Froms    = "Froms"    # Context: export LESS_TERMCAP_us=
        Pn       = "Pn"
        curren   = "curren"   # Context: 'Â¤100'
        halp     = "halp"
        iterm    = "iterm"    # iTerm2
        nd       = "nd"
        ue       = "ue"       # Context: com.apple.metadata

[files]
    extend-exclude = [
        "dotfiles/.assets",
        "dotfiles/Library/Application Support/espanso/match/misspellings.yml",
    ]
