[default]
    locale = "en-us"

    [default.extend-words]
        CMO      = "CMO"      # Chief Marketing Officer
        Enabledi = "Enabledi" # com.apple.metadata
        Froms    = "Froms"    # export LESS_TERMCAP_us=
        Pn       = "Pn"
        brwe     = "brwe"     # used in aliases
        curren   = "curren"   # 'Â¤100'
        halp     = "halp"
        halper   = "halper"
        iterm    = "iterm"    # iTerm2
        kend     = "kend"     #
        nd       = "nd"
        ue       = "ue"       # com.apple.metadata

[files]
    extend-exclude = [
        "dotfiles/.assets",
        "dotfiles/Library/Application Support/espanso/match/misspellings.yml",
    ]
