[packages.apt]
    to_remove = ["btop", "htop"]
    [packages.apt.common]
        packages = [
            "apt-transport-https",
            "bat",                 # cat with syntax highlighting and Git integration
            "curl",
            "dnsutils",
            "fd-find",
            "figlet",
            "fzf",
            "git",
            "git-extras",
            "gnupg",
            "gpg",
            "jq",
            "logrotate",
            "lolcat",
            "mc",                  # Midnight Commander
            "nano",
            "ncdu",                # NCurses Disk Usage
            "needrestart",
            "net-tools",
            "openssh-server",
            "p7zip-full",
            "ripgrep",             # search tool like grep and the silver searcher
            "sudo",
            "tzdata",
            "unzip",
            "wget",
            "zsh",
        ]
    [packages.apt.dev_computer]
        packages = []
    [packages.apt.homelab_member]
        packages = ["iperf"]
    [packages.apt.personal_computer]
        packages = []
[packages.python]
    to_remove = []
    [packages.python.common]
        packages = ["halper", "pygments"]
    [packages.python.dev_computer]
        packages = ["ansible-core", "cookiecutter", "poetry"]
    [packages.python.homelab_member]
        packages = ["git+GITEA_ADDRESS/natelandau/usrbin"]
    [packages.python.personal_computer]
        packages = ["jdfile", "trash-cli", "vid-cleaner"]
[packages.homebrew]
    to_remove = ["btop", "htop", "istat-menus", "rocket", "shotrr"]
    [packages.homebrew.common]
        casks = [
            "1password",
            "1password-cli",
            "espanso",                       # Text expander
            "font-departure-mono",
            "font-jetbrains-mono-nerd-font",
            "font-meslo-lg-dz",
            "font-meslo-lg-nerd-font",
            "git-credential-manager",
            "grandperspective",              # Disk usage visualizer
            "iterm2",                        # Terminal emulator
            "jordanbaird-ice",               # Menu bar customization
            "lingon-x",
            "orbstack",                      # Docker replacement
            "tailscale",
            "visual-studio-code",
        ]
        formulae = [
            "atuin",           # Better shell history
            "bash",
            "bash-completion",
            "bat",             # cat with syntax highlighting and Git integration
            "bottom",          # Process/system monitor for the terminal.
            "chezmoi",         # Dotfile manager
            "coreutils",
            "eza",             # ls replacement
            "fd",              # fd-find
            "findutils",       # GNU find, locate, updatedb, and xargs
            "fzf",             # Fuzzy finder
            "gawk",            # GNU awk
            "git",
            "git-delta",       # https://github.com/dandavison/delta
            "gnu-sed",         # GNU implementation of the famous stream editor
            "gnu-tar",         # GNU version of the tar archiving utility
            "gnutls",          # GNU Transport Layer Security (TLS) Library
            "gping",           # Ping, but with a graph
            "grep",
            "jq",              # Lightweight and flexible command-line JSON processor
            "mas",             # Mac App Store command-line interface
            "mc",              # Midnight Commander
            "most",            # Pager
            "ncdu",            # NCurses Disk Usage
            "ncurses",         # Text-based UI library
            "openssl",         # SSL/TLS cryptography library
            "otree",           # View objects (JSON/YAML/TOML) in TUI tree widget
            "ripgrep",         # search tool like grep and the silver searcher
            "sqlite3",
            "ssh-copy-id",     # Add a public key to a remote machine's authorized_keys file
            "tealdeer",        # TLDR man pages
            "tree",            # Display directories as trees (with optional color/HTML output)
            "uv",              # Python Pyenv, pipx, and packagging replacement
            "vivid",           # https://github.com/sharkdp/vivid
            "wget",
            "zoxide",          # A faster way to navigate your filesystem
            "zsh",
        ]
    [packages.homebrew.dev_computer]
        casks = [
            "bruno",
            "dbeaver-community",
            "fork",
            # "sourcetree", # Alternative to fork
            "lingon-x",
        ]
        formulae = [
            "act",        # runs GitHub Actions locally
            "bats-core",
            "doggo",      # DNS Client
            "gh",         # GitHub CLI
            "git-delta",
            "git-extras",
            "goaccess",
            "gpg",
            "lazygit",    # simple terminal UI for git commands
            "redis",
            "shellcheck",
            "shfmt",
        ]
    [packages.homebrew.homelab_member]
        casks    = ["syncthing", "whatsapp"]
        formulae = ["ffmpeg", "iperf", "nmap", "tailspin"]
    [packages.homebrew.personal_computer]
        casks = [
            "arc",
            "brave-browser",
            "discord",
            "firefox",
            "flux",          # Night Shift
            "fmail2",
            "google-chrome",
            "iina",
            "kap",
            "librewolf",
            "lulu",          # Firewall
            "mimestream",
            "obsidian",
            "plex",
            "raycast",
            "roon",
            "slack",
            "stats",
            "steam",
            "tripmode",
            "whatsapp",
            "zoom",
            # Quick Look plugins
            "qlcolorcode",
            "qlimagesize",
            "qlmarkdown",
            "qlprettypatch",
            "qlstephen",
            "qlvideo",
            "quicklook-csv",
            "quicklook-json",
            "webpquicklook",
        ]
        formulae = []
[packages.mas]
    [packages.mas.common]
        apps = []
    [packages.mas.dev_computer]
        apps = []
    [packages.mas.homelab_member]
        apps = []
    [packages.mas.personal_computer]
        apps = [
            "1091189122", # Bear
            "1136220934", # Infuse
            "1502839586", # Handmirror
            "1532597159", # MP3tag
            "696977615",  # Capo
            "975937182",  # Fantastical
        ]
